#!/bin/bash
echo "mounting cdrom ..."
sleep 1
sudo mount /dev/sr0 /mnt/cdrom
sleep 1
echo "copying data ..."
sleep 1
cp -r -vv /mnt/cdrom/* data
sleep 1
echo "making iso ... "
sleep 1
mkisofs -o iso/cdrom.iso data
sleep 1 
echo "image written to iso/ directory"
