#!/bin/bash
echo "Creating folders ..."
mkdir data && mkdir iso
echo "Creating mount point  ..."
sleep 1 
sudo mkdir /mnt/cdrom
sleep 1
echo "mounting cdrom ..."
sleep 1
sudo mount /dev/sr0 /mnt/cdrom
sleep 1
echo "copying data ..."
sleep 1
cp -r -vv /mnt/cdrom/* data
sleep 1
echo "making iso ... "
sleep 1
mkisofs -o iso/cdrom.iso data
sleep 1 

